.PHONY: all clean distclean watch outline scaffolding strict check stats audit-docs accidents

MAIN = main
LATEXMK = latexmk
UV = uv
# Artifacts removed by `make clean` and after each build.
# `make distclean` additionally removes the PDF and the latexmk tracking files
# ($(MAIN).fdb_latexmk, $(MAIN).fls), forcing a fully fresh rebuild next time.
ARTIFACTS = *.aux *.bbl *.bbl-SAVE-ERROR *.bcf *.bcf-SAVE-ERROR *.blg *.idx *.ilg *.ind *.log *.out *.run.xml *.synctex.gz *.toc

all: $(MAIN).pdf

$(MAIN).pdf: $(MAIN).tex preamble.tex eng-macros.sty frontmatter/*.tex volumes/*/_volume.tex volumes/*/*/chapter.tex appendices/*.tex bibliography/*.bib
	$(LATEXMK) -pdf -interaction=nonstopmode $(MAIN).tex
	rm -f $(ARTIFACTS)

watch:
	$(LATEXMK) -pdf -pvc -interaction=nonstopmode $(MAIN).tex

outline:
	@echo "# Engineering: master outline" > docs/outline.md
	@echo "" >> docs/outline.md
	@echo "_Concatenated from per-volume and per-chapter research dossiers._" >> docs/outline.md
	@echo "_Regenerated by \`make outline\`._" >> docs/outline.md
	@for v in docs/research/*/_volume.md; do \
	    echo "" >> docs/outline.md; \
	    echo "---" >> docs/outline.md; \
	    echo "" >> docs/outline.md; \
	    cat "$$v" >> docs/outline.md; \
	    voldir="$$(dirname "$$v")"; \
	    for c in "$$voldir"/ch*.md; do \
	        [ -f "$$c" ] || continue; \
	        echo "" >> docs/outline.md; \
	        echo "---" >> docs/outline.md; \
	        echo "" >> docs/outline.md; \
	        cat "$$c" >> docs/outline.md; \
	    done; \
	done
	@echo "wrote docs/outline.md"

scaffolding:
	$(UV) run scripts/generate_scaffolding.py

# Strict build: halt on first error. For CI / pre-release verification.
strict:
	$(LATEXMK) -pdf -halt-on-error -interaction=nonstopmode $(MAIN).tex

# Structural check: fails if mandatory metadata is missing from chapter shells.
# Runs over every chapter file under volumes/*/*/chapter.tex.
check:
	@echo "running structural check..."
	@fail=0; \
	for f in volumes/*/*/chapter.tex; do \
	    if ! grep -q '\\chapmeta' "$$f"; then echo "MISSING chapmeta: $$f"; fail=1; fi; \
	    if ! grep -q '\\chapter' "$$f"; then echo "MISSING chapter: $$f"; fail=1; fi; \
	    if ! grep -q '\\label' "$$f"; then echo "MISSING label: $$f"; fail=1; fi; \
	done; \
	if [ $$fail -eq 0 ]; then echo "structural check: PASS ($$(ls volumes/*/*/chapter.tex | wc -l | xargs) chapters)"; \
	else echo "structural check: FAIL"; exit 1; fi

# Stats: counts and sums across the project. Read-only; quick to run.
# Uses fgrep / fixed-string grep to avoid the BRE/ERE backslash trap in Makefile recipes.
stats:
	@echo "=== Engineering project stats ==="
	@printf "Volumes:               %s\n" "$$(ls -d volumes/*/ | wc -l | xargs)"
	@printf "Chapter shells:        %s\n" "$$(ls volumes/*/*/chapter.tex | wc -l | xargs)"
	@printf "Per-volume dossiers:   %s\n" "$$(ls docs/research/*/_volume.md | wc -l | xargs)"
	@printf "Per-chapter dossiers:  %s\n" "$$(ls docs/research/*/ch*.md | wc -l | xargs)"
	@printf "TODO markers (TeX):    %s\n" "$$(grep -rhF '\TODO' volumes/ frontmatter/ appendices/ | wc -l | xargs)"
	@printf "Half-life: TBD count:  %s\n" "$$(grep -rhF 'Half-life: TBD' volumes/ | wc -l | xargs)"
	@printf "Empty epigraphs:       %s\n" "$$(grep -rhF '\epigraph{}{}' volumes/ | wc -l | xargs)"
	@printf "Section headings:      %s\n" "$$(grep -rhF '\section{' volumes/ appendices/ | wc -l | xargs)"
	@printf "Chapmeta blocks:       %s\n" "$$(grep -rhF '\chapmeta{' volumes/ | wc -l | xargs)"
	@printf "Bibliography entries:  %s\n" "$$(grep -c '^@' bibliography/references.bib | xargs)"

# Audit docs for stale references introduced before Phase 0.6 expansion.
# Flags occurrences that should normally be 174 chapters / ~491 pages /
# the per-volume dossier path pattern. The diagnostic file is excluded
# because it legitimately quotes the pre-expansion state.
audit-docs:
	@echo "auditing docs for stale references..."
	@found=0; \
	scan_paths="README.md scripts appendices frontmatter"; \
	doc_paths="$$(find docs -name '*.md' ! -path 'docs/diagnostic.md' ! -path 'docs/research/accidents/*')"; \
	for token in '163 chapter' '163 chapters' '~465' '465 page' 'book-NN' 'book-XX' 'docs/research/book-' 'Volume XI Chapter 12' '/Users/' '/home/'; do \
	    hits=$$(grep -rnF -- "$$token" $$scan_paths $$doc_paths 2>/dev/null || true); \
	    if [ -n "$$hits" ]; then \
	        echo ""; \
	        echo "STALE: $$token"; \
	        echo "$$hits"; \
	        found=1; \
	    fi; \
	done; \
	if [ $$found -eq 0 ]; then echo "audit-docs: PASS (no stale references)"; \
	else echo ""; echo "audit-docs: FAIL"; exit 1; fi

# Named-cases registry audit (Q56). For every \cite{acc:*} key in chapter
# prose, verify a registry entry exists at docs/research/accidents/ that
# names the same key in its frontmatter or body. Lists registry entries
# not yet cited as informational. Exits non-zero if any cited acc: key
# lacks a registry entry.
accidents:
	@echo "auditing chapter prose for named accidents..."
	@cited=$$(grep -rhoE 'acc:[A-Za-z0-9_:.-]+' volumes/ 2>/dev/null | sort -u); \
	registry_dir=docs/research/accidents; \
	if [ ! -d "$$registry_dir" ]; then \
	    echo "registry directory $$registry_dir does not exist"; exit 1; \
	fi; \
	registered=$$(grep -rhE 'acc:[A-Za-z0-9_:.-]+' $$registry_dir 2>/dev/null \
	    | grep -oE 'acc:[A-Za-z0-9_:.-]+' | sort -u); \
	missing=""; \
	for key in $$cited; do \
	    if ! echo "$$registered" | grep -qx "$$key"; then \
	        missing="$$missing $$key"; \
	    fi; \
	done; \
	if [ -n "$$missing" ]; then \
	    echo ""; \
	    echo "MISSING from registry:$$missing"; \
	    echo ""; \
	    echo "accidents: FAIL"; \
	    exit 1; \
	fi; \
	cited_count=$$(echo "$$cited" | grep -c '^acc:' 2>/dev/null || echo 0); \
	entry_count=$$(ls $$registry_dir/*.md 2>/dev/null \
	    | grep -v -E '/(README|SCHEMA)\.md$$' | wc -l | xargs); \
	echo "$$cited_count acc: keys cited in chapters; all resolve to a registry entry"; \
	echo "$$entry_count registry entries on disk (excluding README, SCHEMA)"; \
	echo "accidents: PASS"

clean:
	rm -f $(ARTIFACTS)

distclean:
	rm -f $(ARTIFACTS) $(MAIN).pdf $(MAIN).fdb_latexmk $(MAIN).fls
