.PHONY: all clean distclean watch outline scaffolding strict check stats audit-docs accidents exercise-counts

MAIN = main
LATEXMK = latexmk
UV = uv
# Artifacts removed by `make clean` and after each build.
# `make distclean` additionally removes the PDF and the latexmk tracking files
# ($(MAIN).fdb_latexmk, $(MAIN).fls), forcing a fully fresh rebuild next time.
ARTIFACTS = *.aux *.bbl *.bbl-SAVE-ERROR *.bcf *.bcf-SAVE-ERROR *.blg *.idx *.ilg *.ind *.log *.out *.run.xml *.synctex.gz *.toc

all: $(MAIN).pdf

$(MAIN).pdf: $(MAIN).tex preamble.tex eng-macros.sty frontmatter/*.tex volumes/*/_volume.tex volumes/*/*/chapter.tex appendices/*.tex bibliography/*.bib
	$(LATEXMK) -pdf -interaction=nonstopmode $(MAIN).tex
	rm -f $(ARTIFACTS)

watch:
	$(LATEXMK) -pdf -pvc -interaction=nonstopmode $(MAIN).tex

outline:
	@echo "# Engineering: master outline" > docs/outline.md
	@echo "" >> docs/outline.md
	@echo "_Concatenated from per-volume and per-chapter research dossiers._" >> docs/outline.md
	@echo "_Regenerated by \`make outline\`._" >> docs/outline.md
	@for v in docs/research/*/_volume.md; do \
	    echo "" >> docs/outline.md; \
	    echo "---" >> docs/outline.md; \
	    echo "" >> docs/outline.md; \
	    cat "$$v" >> docs/outline.md; \
	    voldir="$$(dirname "$$v")"; \
	    for c in "$$voldir"/ch*.md; do \
	        [ -f "$$c" ] || continue; \
	        echo "" >> docs/outline.md; \
	        echo "---" >> docs/outline.md; \
	        echo "" >> docs/outline.md; \
	        cat "$$c" >> docs/outline.md; \
	    done; \
	done
	@echo "wrote docs/outline.md"

scaffolding:
	$(UV) run scripts/generate_scaffolding.py

# Strict build: halt on first error. For CI / pre-release verification.
strict:
	$(LATEXMK) -pdf -halt-on-error -interaction=nonstopmode $(MAIN).tex

# Structural check: fails if mandatory metadata is missing from chapter shells.
# Runs over every chapter file under volumes/*/*/chapter.tex.
check:
	@echo "running structural check..."
	@fail=0; \
	for f in volumes/*/*/chapter.tex; do \
	    if ! grep -q '\\chapmeta' "$$f"; then echo "MISSING chapmeta: $$f"; fail=1; fi; \
	    if ! grep -q '\\chapter' "$$f"; then echo "MISSING chapter: $$f"; fail=1; fi; \
	    if ! grep -q '\\label' "$$f"; then echo "MISSING label: $$f"; fail=1; fi; \
	done; \
	if [ $$fail -eq 0 ]; then echo "structural check: PASS ($$(ls volumes/*/*/chapter.tex | wc -l | xargs) chapters)"; \
	else echo "structural check: FAIL"; exit 1; fi

# Stats: counts and sums across the project. Read-only; quick to run.
# Uses fgrep / fixed-string grep to avoid the BRE/ERE backslash trap in Makefile recipes.
stats:
	@echo "=== Engineering project stats ==="
	@printf "Volumes:               %s\n" "$$(ls -d volumes/*/ | wc -l | xargs)"
	@printf "Chapter shells:        %s\n" "$$(ls volumes/*/*/chapter.tex | wc -l | xargs)"
	@printf "Per-volume dossiers:   %s\n" "$$(ls docs/research/*/_volume.md | wc -l | xargs)"
	@printf "Per-chapter dossiers:  %s\n" "$$(ls docs/research/*/ch*.md | wc -l | xargs)"
	@printf "TODO markers (TeX):    %s\n" "$$(grep -rhF '\TODO' volumes/ frontmatter/ appendices/ | wc -l | xargs)"
	@printf "Half-life: TBD count:  %s\n" "$$(grep -rhF 'Half-life: TBD' volumes/ | wc -l | xargs)"
	@printf "Empty epigraphs:       %s\n" "$$(grep -rhF '\epigraph{}{}' volumes/ | wc -l | xargs)"
	@printf "Section headings:      %s\n" "$$(grep -rhF '\section{' volumes/ appendices/ | wc -l | xargs)"
	@printf "Chapmeta blocks:       %s\n" "$$(grep -rhF '\chapmeta{' volumes/ | wc -l | xargs)"
	@printf "Bibliography entries:  %s\n" "$$(grep -c '^@' bibliography/references.bib | xargs)"

# Audit docs for stale references introduced before Phase 0.6 expansion.
# Flags occurrences that should normally be 174 chapters / ~491 pages /
# the per-volume dossier path pattern. The diagnostic file is excluded
# because it legitimately quotes the pre-expansion state.
audit-docs:
	@echo "auditing docs for stale references..."
	@found=0; \
	scan_paths="README.md scripts appendices frontmatter"; \
	doc_paths="$$(find docs -name '*.md' ! -path 'docs/diagnostic.md' ! -path 'docs/research/accidents/*')"; \
	for token in '163 chapter' '163 chapters' '~465' '465 page' 'book-NN' 'book-XX' 'docs/research/book-' 'Volume XI Chapter 12' '/Users/' '/home/'; do \
	    hits=$$(grep -rnF -- "$$token" $$scan_paths $$doc_paths 2>/dev/null || true); \
	    if [ -n "$$hits" ]; then \
	        echo ""; \
	        echo "STALE: $$token"; \
	        echo "$$hits"; \
	        found=1; \
	    fi; \
	done; \
	if [ $$found -eq 0 ]; then echo "audit-docs: PASS (no stale references)"; \
	else echo ""; echo "audit-docs: FAIL"; exit 1; fi

# Named-cases registry audit (Q56). Two checks:
#   (a) For every \cite{acc:*} key in chapter prose, verify a registry entry
#       exists at docs/research/accidents/ that names the same key.
#   (b) For every canonical accident name in any registry entry's frontmatter,
#       scan chapter prose (excluding the \chapmeta metadata block) for the
#       name; if found, require that the entry's primary or closest-equivalent
#       citation key appear at least once in the chapter via \cite{}.
# (a) catches a citation to a missing registry entry; (b) catches a chapter
# that names an accident in prose without citing the registry's entry.
accidents:
	@echo "auditing chapter prose for named accidents..."
	@registry_dir=docs/research/accidents; \
	if [ ! -d "$$registry_dir" ]; then \
	    echo "registry directory $$registry_dir does not exist"; exit 1; \
	fi; \
	cited=$$(grep -rhoE 'acc:[A-Za-z0-9_:.-]+' volumes/ 2>/dev/null | sort -u); \
	registered=$$(grep -rhoE 'acc:[A-Za-z0-9_:.-]+' $$registry_dir 2>/dev/null | sort -u); \
	missing=""; \
	for key in $$cited; do \
	    if ! echo "$$registered" | grep -qx "$$key"; then \
	        missing="$$missing $$key"; \
	    fi; \
	done; \
	if [ -n "$$missing" ]; then \
	    echo ""; \
	    echo "MISSING from registry (cited acc: keys without entries):$$missing"; \
	    echo ""; \
	    echo "accidents: FAIL"; \
	    exit 1; \
	fi; \
	prose_violations=""; \
	for entry in $$registry_dir/*.md; do \
	    base=$$(basename $$entry); \
	    [ "$$base" = "README.md" ] && continue; \
	    [ "$$base" = "SCHEMA.md" ] && continue; \
	    name=$$(awk -F': *' '/^name:/{print $$2; exit}' $$entry); \
	    [ -z "$$name" ] && continue; \
	    entry_keys=$$(grep -oE '(acc|paper|text|web|hist):[A-Za-z0-9_:.-]+' $$entry | sort -u); \
	    for chapter in volumes/*/*/chapter.tex; do \
	        prose=$$(awk '/\\chapmeta\{/{in_meta=1; next} in_meta{ if (/\}/) in_meta=0; next} {print}' $$chapter); \
	        if echo "$$prose" | grep -q -F "$$name"; then \
	            chapter_cites=$$(grep -oE '\\cite\{[^}]*\}' $$chapter | grep -oE '(acc|paper|text|web|hist):[A-Za-z0-9_:.-]+' || true); \
	            found=0; \
	            for ek in $$entry_keys; do \
	                if echo "$$chapter_cites" | grep -qx "$$ek"; then \
	                    found=1; break; \
	                fi; \
	            done; \
	            if [ $$found -eq 0 ]; then \
	                prose_violations="$$prose_violations|$$chapter names \"$$name\" without a registry citation"; \
	            fi; \
	        fi; \
	    done; \
	done; \
	if [ -n "$$prose_violations" ]; then \
	    echo ""; \
	    echo "PROSE-NAMED accidents without registry citation:"; \
	    echo "$$prose_violations" | tr '|' '\n' | grep -v '^$$' | sed 's/^/  /'; \
	    echo ""; \
	    echo "accidents: FAIL"; \
	    exit 1; \
	fi; \
	cited_count=$$(echo "$$cited" | grep -c '^acc:' 2>/dev/null || echo 0); \
	entry_count=$$(ls $$registry_dir/*.md 2>/dev/null \
	    | grep -v -E '/(README|SCHEMA)\.md$$' | wc -l | xargs); \
	echo "$$cited_count acc: keys cited in chapters; all resolve to a registry entry"; \
	echo "registry prose-name scan: PASS (every named accident has at least one of its registry keys cited)"; \
	echo "$$entry_count registry entries on disk (excluding README, SCHEMA)"; \
	echo "accidents: PASS"

# Exercise-count check. For each chapter with prose (i.e. at least one
# \begin{exercise} block), verify that the count of \begin{exercise} blocks
# matches the "Exercise target: N" line in the chapter's \chapmeta. Skips
# chapters that are still scaffolding shells (no exercise blocks yet).
exercise-counts:
	@echo "checking per-chapter exercise counts against chapmeta targets..."
	@fail=0; checked=0; \
	for chapter in volumes/*/*/chapter.tex; do \
	    target=$$(grep -oE 'Exercise target: *[0-9]+' $$chapter | head -1 | grep -oE '[0-9]+'); \
	    [ -z "$$target" ] && continue; \
	    actual=$$(grep -c '\\begin{exercise}' $$chapter); \
	    [ "$$actual" -eq 0 ] && continue; \
	    checked=$$((checked + 1)); \
	    if [ "$$target" != "$$actual" ]; then \
	        echo "  $$chapter: target $$target, actual $$actual"; \
	        fail=1; \
	    fi; \
	done; \
	if [ $$fail -eq 0 ]; then \
	    echo "exercise-counts: PASS ($$checked chapters with prose match their chapmeta target)"; \
	else \
	    echo ""; \
	    echo "exercise-counts: FAIL"; \
	    exit 1; \
	fi

clean:
	rm -f $(ARTIFACTS)

distclean:
	rm -f $(ARTIFACTS) $(MAIN).pdf $(MAIN).fdb_latexmk $(MAIN).fls
