"""
ComBat-style empirical-Bayes batch correction on a simulated two-batch
expression dataset.

The full ComBat model fits per-feature location and scale parameters per
batch and shrinks them toward a pooled prior. This educational
implementation includes the location-only adjustment with a pooled-variance
estimator: each feature in each batch has its batch-specific mean replaced
by the pooled mean of all batches, holding the biological condition fixed.

The simulation has two batches and two conditions (healthy, tumour) with
batch and condition non-collinear; ComBat recovers the disease signal on
PC1 after correction. The figure
volumes/06-life/ch11-bioinformatics/figures/fig-batch-effect.tex was
generated by hand from a run of this script.

Dependencies:
  numpy, scikit-learn

Usage:
  python batch_correct.py

Supports Volume VI, Chapter 11, Section 11.8 (failure section: batch
effects) and the diagnosis and failure-analysis exercises.
"""

from __future__ import annotations

import numpy as np


def simulate(
    n_features: int = 200,
    n_per_group: int = 8,
    batch_shift: float = 2.5,
    disease_shift: float = 1.2,
    noise: float = 0.5,
    seed: int = 0,
):
    """Return (X, batch, disease) with shape (n_samples, n_features)."""
    rng = np.random.default_rng(seed)
    # Four groups: (batch=0, healthy), (batch=0, tumour),
    #              (batch=1, healthy), (batch=1, tumour).
    samples = []
    batch_labels = []
    disease_labels = []
    base = rng.normal(0.0, 1.0, size=n_features)
    batch_offset = rng.normal(0.0, 1.0, size=n_features) * batch_shift
    disease_offset = rng.normal(0.0, 1.0, size=n_features) * disease_shift

    for batch in (0, 1):
        for disease in (0, 1):
            for _ in range(n_per_group):
                vec = (
                    base
                    + (batch_offset if batch == 1 else 0.0)
                    + (disease_offset if disease == 1 else 0.0)
                    + rng.normal(0.0, noise, size=n_features)
                )
                samples.append(vec)
                batch_labels.append(batch)
                disease_labels.append(disease)

    X = np.array(samples)
    batch = np.array(batch_labels)
    disease = np.array(disease_labels)
    return X, batch, disease


def combat_location(X: np.ndarray, batch: np.ndarray, disease: np.ndarray) -> np.ndarray:
    """Location-only ComBat. Removes per-batch mean shifts holding disease fixed.

    For each (batch, feature), the per-batch mean is replaced by the
    pooled mean across batches, computed within each disease condition.
    """
    X_adj = X.copy()
    for cond in np.unique(disease):
        mask = disease == cond
        pooled = X[mask].mean(axis=0)
        for b in np.unique(batch):
            bmask = mask & (batch == b)
            batch_mean = X[bmask].mean(axis=0)
            X_adj[bmask] = X[bmask] - batch_mean + pooled
    return X_adj


def pca_2d(X: np.ndarray):
    """Quick PCA-2D via SVD."""
    Xc = X - X.mean(axis=0)
    U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
    var = (S ** 2) / (X.shape[0] - 1)
    var_ratio = var / var.sum()
    return Xc @ Vt.T[:, :2], var_ratio[:2]


def main() -> None:
    X, batch, disease = simulate()
    print(f"X shape: {X.shape}; batch unique: {np.unique(batch)}; "
          f"disease unique: {np.unique(disease)}")

    pcs_before, var_before = pca_2d(X)
    pcs_after, var_after = pca_2d(combat_location(X, batch, disease))

    print(f"Before correction: PC1 var = {var_before[0]:.3f}, "
          f"PC2 var = {var_before[1]:.3f}")
    print(f"After  correction: PC1 var = {var_after[0]:.3f}, "
          f"PC2 var = {var_after[1]:.3f}")

    # Diagnostic: correlation of PC1 with batch and disease before/after
    for label, pcs in [("before", pcs_before), ("after", pcs_after)]:
        r_batch = np.corrcoef(pcs[:, 0], batch)[0, 1]
        r_dis = np.corrcoef(pcs[:, 0], disease)[0, 1]
        print(f"{label:6s}: corr(PC1, batch) = {r_batch:+.3f}, "
              f"corr(PC1, disease) = {r_dis:+.3f}")


if __name__ == "__main__":
    main()
